enyo.depends(
    "ModelControllerExtended.js",
    "ListsController.js",
    "ListsRowController.js",
    "CollectionRepeaterControllerExtended.js",
    "ProxyController.js",
    "SelectedListController.js",
    "SelectedItemController.js"
);