enyo.depends(
    "$lib/layout",
    "$lib/onyx",
    "$lib/mvc",
    "$lib/localstorage/backbone.localStorage.js",
    "css",
    "apps",
    "controllers",
    "models",
    "views",
    "start.js"
);